name: Prebuild SQLite assets

on:
  workflow_call:
    outputs:
      artifact_url:
        description: "URL of the artifact containing precompiled SQLite binaries"
        value: ${{ jobs.compile.outputs.artifact_url }}
      artifact_id:
        description: "id of the artifact containing precompiled SQLite binaries"
        value: ${{ jobs.compile.outputs.artifact_id }}

jobs:
  compile:
    name: Compile SQLite
    timeout-minutes: 30
    runs-on: macos-latest
    outputs:
      artifact_url: ${{ steps.upload.outputs.artifact-url }}
      artifact_id: ${{ steps.upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        id: cache_prebuild
        with:
          path: internal/prebuild-binaries/build/output
          key: sqlite-build-${{ hashFiles('internal/prebuild-binaries', 'plugins/build-plugin') }}

      - name: Validate Gradle Wrapper
        if: steps.cache_prebuild.outputs.cache-hit != 'true'
        uses: gradle/actions/wrapper-validation@v4
      - uses: actions/cache@v4
        if: steps.cache_prebuild.outputs.cache-hit != 'true'
        with:
          path: ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
      - name: Set up JDK 25
        if: steps.cache_prebuild.outputs.cache-hit != 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
      - name: Set up Gradle
        if: steps.cache_prebuild.outputs.cache-hit != 'true'
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Set up XCode
        if: steps.cache_prebuild.outputs.cache-hit != 'true'
        uses: maxim-lobanov/setup-xcode@v1
      - name: Setup Linux build docker image
        run: docker build -t powersync_kotlin_sqlite3mc_build_helper --load jni
      - name: Download llvm-mingw
        run: |
          curl -L https://github.com/mstorsjo/llvm-mingw/releases/download/20251118/llvm-mingw-20251118-ucrt-macos-universal.tar.xz -o llvm-ming.tar.xz
          tar --extract --gzip --file llvm-ming.tar.xz
          rm llvm-ming.tar.xz

      - name: Compile SQLite with Gradle
        if: steps.cache_prebuild.outputs.cache-hit != 'true'
        run: |
          ./gradlew --scan -PllvmMingw=$(pwd)/llvm-mingw-20251118-ucrt-macos-universal internal:prebuild-binaries:compileNative
        shell: bash
      - uses: actions/upload-artifact@v5
        id: upload
        with:
          path: internal/prebuild-binaries/build/output/*
          name: kotlin-sqlite
          retention-days: 1
      - run: |
          echo "${{ steps.upload.outputs.artifact-url }}"
